# Generated by Django 4.0.6 on 2022-08-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-created']},
        ),
    ]
